[
{	'position' : [3,3],
	'model' : 'barrel',
	'name' : 'Barrel',
	'health' : 200,
	'hp' : 200,
	'spirit' : 0,
	'sp' : 0,
	'move' : 0,
	'mv' : 0,
	'actions' : 0,
	'act' : 0,
	'strength' : 0,
	'intelligence' : 0,
	'toughness' : 10,
	'willpower' : 0,
	'focus' : 0,
	'agility' : 0,
	'speed' : 0,
	'jump' : 0,
	'regen' : 0,
	'commands' : [[]]
},
{	'position' : [1,0],
	'model' : 'soldier',
	'name' : 'Shino',
	'health' : 1100,
	'hp' : 1100,
	'spirit' : 400,
	'sp' : 0,
	'move' : 5,
	'mv' : 5,
	'actions' : 1,
	'act' : 1,
	'strength' : 120,
	'intelligence' : 70,
	'toughness' : 120,
	'willpower' : 60,
	'focus' : 110,
	'agility' : 90,
	'speed' : 19,
	'jump' : 12,
	'regen' : 5,
	'commands' :	[['slash', 'gloryStrike', 'frontlineSlash', 'doubleSlash', 'ribbonDash', 'predatorsDescent', 'ebber', 'cleave'],
					['strengthen', 'focus', 'dualSharpen', 'dash']]
},
{ 	'position' : [3,0],
	'model' : 'soldier',
	'name' : 'Haro',
	'health' : 1100,
	'hp' : 1100,
	'spirit' : 400,
	'sp' : 0,
	'move' : 5,
	'mv' : 5,
	'actions' : 1,
	'act' : 1,
	'strength' : 120,
	'intelligence' : 70,
	'toughness' : 120,
	'willpower' : 60,
	'focus' : 110,
	'agility' : 90,
	'speed' : 19,
	'jump' : 12,
	'regen' : 5,
	'commands' : 	[['slash', 'gloryStrike', 'frontlineSlash', 'doubleSlash', 'ribbonDash', 'predatorsDescent', 'ebber', 'cleave'],
					['strengthen', 'focus', 'dualSharpen', 'dash']]
},
{	'position' : [1,1],
	'model' : 'devoted',
	'name' : 'Urchin',
	'health' : 800,
	'hp' : 800,
	'spirit' : 700,
	'sp' : 0,
	'move' : 4,
	'mv' : 4,
	'actions' : 1,
	'act' : 1,
	'strength' : 40,
	'intelligence' : 120,
	'toughness' : 60,
	'willpower' : 120,
	'focus' : 110,
	'agility' : 90,
	'speed' : 14,
	'jump' : 10,
	'regen' : 7,
	'commands' : 	[['psiStrike', 'flameBarrage', 'mudshot', 'aeroImpact', 'meteor', 'galeCloak'],
					['smarten', 'tutor', 'study', 'dash']]
},
{	'position' : [2,1],
	'model' : 'devoted',
	'name' : 'Lish',
	'health' : 800,
	'hp' : 800,
	'spirit' : 700,
	'sp' : 0,
	'move' : 4,
	'mv' : 4,
	'actions' : 1,
	'act' : 1,
	'strength' : 40,
	'intelligence' : 120,
	'toughness' : 60,
	'willpower' : 120,
	'focus' : 110,
	'agility' : 90,
	'speed' : 14,
	'jump' : 10,
	'regen' : 7,
	'commands' : 	[['psiStrike', 'flameBarrage', 'mudshot', 'aeroImpact', 'meteor', 'galeCloak'],
					['smarten', 'tutor', 'study', 'dash']]
}
]
